---
title: "Warrents Research"
output: 
  flexdashboard::flex_dashboard:
    orientation: column
    vertical_layout: fill
    theme: simplex
editor_options: 
  chunk_output_type: console
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(RSocrata)
library(here)
library(tidyverse)
library(plotrix)
library(plyr) 
library(maps)
data(world.cities)
library(rbokeh)
library(Rcpp)
library(dplyr)
library(widgetframe)

if(!requireNamespace("devtools")) install.packages("devtools")
devtools::install_github("dkahle/ggmap", ref = "tidyup")
library(ggmap)

source(here::here('Main/tokenSocrata.R'))
```

<!-- Warrants Database -->

```{r}
warants <- 'https://data.brla.gov/resource/gdjb-agbb.csv?'
query <- "$where=doa between '2014-06-12' and '2016-05-12'"
dt_warrants <- read.socrata(paste0(warants, query), app_token = token[['app']])
dt_warrants <- as_tibble(dt_warrants)
```

Column {data-width=600}
-------------------------------------

### Warrants by States

```{r}
caps <- dplyr::filter(world.cities, country.etc =="USA")
caps$name <- toupper(caps$name)
colnames(dt_warrants)[6] <- "blah"
colnames(dt_warrants)[1] <- "name"

dt_warrants$name <- toupper(dt_warrants$name)

x <- merge(x = caps, y = dt_warrants)

s <- count(x$name)
colnames(s)[1] <- "name"

blah <- merge(x = x, y = s, by = "name", all = TRUE) 
kharya <- distinct(blah, name, freq,lat,long, pop)
colnames(kharya)[1] <- "Location"
colnames(kharya)[5] <- "Amount"
colnames(kharya)[2] <- "Population"

plot <- suppressWarnings(figure(width = 600, height = 400, padding_factor = 0) %>%
  ly_map("world", col = "gray") %>%
  ly_points(long, lat, data = kharya, size = 5,
            hover = c(Location, Population, Amount)))

frameWidget(plot,width=600,height=400)
```

Row {.tabset .tabset-fade}
-------------------------------------

### Types of Crimes

```{r}
temp <- dt_warrants %>%
  filter(type != "CCC" & type != "PKCONA") %>%
  mutate(type = case_when(
    type == "CMISD" ~ "Criminal Misdemeanor",
    type == "DV" ~ "Domestic Violence",
    type == "CCTRAF" ~ "Traffic Offense",
    type == "PP" ~ "Partial Payment Account",
    type == "CCDWI" ~ "Driving While Intoxicated"
    ))

tempLabels <- c("1","2","3","4", "5")

ggplot(data = temp) +
  geom_bar(aes(x = type, fill = type), color = "black") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(title = "Types of Crimes", y = "Number of Warrants", x = "Crime Type", fill = "Color") + scale_x_discrete(labels = tempLabels)
```

### Warrants Issued by Gender

```{r}
dt_warrants %>%
  filter(sex != "" & sex != "O") %>%
  ggplot() + geom_bar(aes(x = 'warrants', fill = sex), position = 'fill')+ 
    labs(title = "Warrants Issued by Gender", x = "", y = "Amount")
```

### Crimes by Gender

```{r}
dt_warrants %>%
  filter(sex != "" & sex != "O") %>%
  ggplot() +
    geom_bar(aes(x = type, fill = sex), color = "black", position = 'dodge', alpha = .90) +
    ggtitle('Crimes by Gender') + xlab("Crime Type") + ylab("Warrants Amount") + labs(fill ='Sex') + theme(axis.text.x = element_text(angle = 45, hjust = 1))
```